server:
  port: 8083

spring:
  kafka:
    # 这里如果是windows环境需要配置C:\Windows\System32\drivers\etc\hosts文件的node2对应的ip地址，如：192.168.49.130 node2
    bootstrap-servers: node2:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: test-consumer-group